### ISSUE TITLE
Add an SSL Certificate

### ISSUE THREAD

**Issue by Soben** [civicdata/civicdata.github.io#132] opened 2019-09-30 14:50 UTC
https://cl.ly/41b96cadf518

Missing SSL Certificate, which immediately pops up when visiting Brave since it enforces SSL. Chrome will soon be enforcing SSL too.

**Comment by thebouv** [comment] 2019-09-30 15:02
Just a redirect to fix as www is not the host we have secured.

https://civicdataalliance.org/

So we're not missing SSL, just don't have one on www.  We can either add www as part of the SAN, or just set up hosting rule to 301 www to non-www root.

**Comment by thebouv** [comment] 2019-10-14 13:17
@Soben Can you confirm this is resolved for you?

**Comment by Soben** [comment] 2019-10-14 19:38
Hey @thebouv 

For me, if I enter http://www.civicdataalliance.org it does correctly redirect to https://civicdataalliance.org

However, if I go straight to https://www.civicdataalliance.org I continue to get the same secure warning.

**Comment by thebouv** [comment] 2019-10-15 00:38
Ah! Thanks, I went back to go do this and thought it was resolved from someone else. I'll see if I can get this redirecting properly then. Thanks.

**Comment by mgottholsen** [comment] 2019-10-16 22:21
This should be fixed now. It was caused by the Github Pages option to "Enforce HTTPS". Please double check and let me know if it's working now.

**Comment by mgottholsen** [comment] 2019-10-18 14:51
There's a work around that can be done with Cloudflare (see [this page](https://github.community/t5/GitHub-Pages/Does-GitHub-Pages-Support-HTTPS-for-www-and-subdomains/td-p/7116) for a good description of this problem). We'll have to do some changes to how the site is served to correct this, but I'm going to close this issue.

**Closed as completed by mgottholsen** 2019-10-18 14:51 UTC
